apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: kubeplugin
spec:
  version: "v0.0.1"
  homepage: https://github.com/PTarasyuk/kubeplugin
  shortDescription: "Displays CPU/Memory usage for a resource type (Pod/Node) in a namespace"
  platforms:
  - selector:
      matchExpressions:
      - key: "os"
        operator: "In"
        values:
        - darwin
        - linux
    uri: https://github.com/PTarasyuk/kubeplugin/archive/v0.0.1.zip
    sha256: 164720980e2f90867bc2d6d9c7e8a3130b9b6c0887e78ce83808ef19c425eb0a
    files:
    - from: "/kubeplugin-0.0.1/scripts/kubeplugin"
      to: .
    bin: kubeplugin